#
#  GitLab CI/CD configuration.
#
#  Copyright (C)
#  Honda Research Institute Europe GmbH
#  Carl-Legien-Str. 30
#  63073 Offenbach/Main
#  Germany
#
#  UNPUBLISHED PROPRIETARY MATERIAL.
#  ALL RIGHTS RESERVED.
#
#

stages:
    - venv
    - check
    - test

variables:
    PIP_INDEX_URL: https://cicd-pkg-reg.honda-ri.de/repository/pypi-proxy/simple
    REQUESTS_CA_BUNDLE: /usr/local/share/ca-certificates/HRI-CA_cert.crt

default:
    image: dmz-gitlab.honda-ri.de:5050/gitlabrunner/buildcontainers/hri-eu-main:latest

create venv:
    stage: venv
    before_script:
        - sed --in-place 's|^git+https://dmz-gitlab.honda-ri.de/|git+https://gitlab-ci-token:${CI_JOB_TOKEN}@dmz-gitlab.honda-ri.de/|g' ./requirements.txt
    script:
        - ./create_venv.sh --ci-only
    artifacts:
        paths:
            - venv
        expire_in: 1h

bst checks:
    stage: check
    script:
        - ./ci-bst-checks.sh
    needs: [ ]

lint:
    stage: check
    script:
        - source venv/bin/activate
        - ./ci-lint.sh | tee pylint.report
    artifacts:
        paths:
            - pylint.report
        expire_in: 1 hour

black:
    stage: check
    script:
        - source venv/bin/activate
        - ./ci-format.sh

mypy:
    stage: check
    when: manual
    script:
        - source venv/bin/activate
        - ./ci-mypy.sh

unit tests:
    stage: test
    #when: manual
    script:
        - source venv/bin/activate
        - ./ci-unit-tests.sh
        - coverage xml
    coverage: '/^TOTAL.+?(\d+\%)$/'
    artifacts:
        reports:
            junit:
                - junit-report.xml
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
        paths:
            - junit-report.xml
            - coverage.xml
        expire_in: 1 hour
