#
#  GitLab CI/CD configuration.
#
#  Copyright (C)
#  Honda Research Institute Europe GmbH
#  Carl-Legien-Str. 30
#  63073 Offenbach/Main
#  Germany
#
#  UNPUBLISHED PROPRIETARY MATERIAL.
#  ALL RIGHTS RESERVED.
#
#

stages:
    - venv
    - check
    - test

variables:
    PIP_INDEX_URL: https://package-cache.honda-ri.de/repository/pypi-proxy/simple
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    REQUESTS_CA_BUNDLE: /usr/local/share/ca-certificates/HRI-CA_cert.crt

default:
    image: dmz-gitlab.honda-ri.de:5050/tech_team/docker/ubuntu2004-hri-main:1.1

.checkout-from-dmz:
    before_script:
        - git config --global --add safe.directory '*'
        - git config --global http.sslVerify "false"
        - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@dmz-gitlab.honda-ri.de/robotics/".insteadOf
            https://github.com/HRI-EU/
        - git submodule sync --recursive
        - git submodule update --init --force
        - git submodule sync --recursive
        - git submodule update --init --force --recursive

create venv:
    stage: venv
    script:
        - ./create_venv.sh
    #    artifacts:
    #        paths:
    #            - venv
    #        expire_in: 1h
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - venv

bst checks:
    stage: check
    script:
        - ./ci-bst-checks.sh
    needs: [ ]

lint:
    stage: check
    script:
        - source venv/bin/activate
        - ./ci-lint.sh | tee pylint.report
    artifacts:
        paths:
            - pylint.report
        expire_in: 1 hour
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - venv

black:
    stage: check
    script:
        - source venv/bin/activate
        - ./ci-format.sh
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - venv

mypy:
    stage: check
    when: manual
    script:
        - source venv/bin/activate
        - ./ci-mypy.sh
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - venv

unit tests:
    stage: test
    before_script:
        - !reference [ .checkout-from-dmz, before_script ]
        - sed --in-place 's|^git+https://dmz-gitlab.honda-ri.de/|git+https://gitlab-ci-token:${CI_JOB_TOKEN}@dmz-gitlab.honda-ri.de/|g' ./requirements.txt
    script:
        - source venv/bin/activate
#        - ./create_venv.sh
        - ./ci-unit-tests.sh
        - coverage xml
    coverage: '/^TOTAL.+?(\d+\%)$/'
    artifacts:
        reports:
            junit:
                - junit-report.xml
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
        paths:
            - junit-report.xml
            - coverage.xml
        expire_in: 1 hour
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - venv
