#
#  GitLab CI/CD configuration.
#
#  Copyright (C)
#  Honda Research Institute Europe GmbH
#  Carl-Legien-Str. 30
#  63073 Offenbach/Main
#  Germany
#
#  UNPUBLISHED PROPRIETARY MATERIAL.
#  ALL RIGHTS RESERVED.
#
#

stages:
    - check
    - test
    - quality assurance

default:
    image: dmz-gitlab.honda-ri.de:5050/gitlabrunner/buildcontainers/care_ros_ws:latest

bst checks:
    stage: check
    script:
        - ./ci-bst-checks.sh
    needs: [ ]

lint:
    stage: check
    script:
        - ./ci-lint.sh | tee pylint.report
    artifacts:
        paths:
            - pylint.report
        expire_in: 1 hour
    needs: [ ]

black:
    stage: check
    script:
        - ./ci-format.sh
    needs: [ ]

unit tests:
    stage: test
    script:
        - ./ci-unit-tests.sh
        - coverage xml
    coverage: '/^TOTAL.+?(\d+\%)$/'
    artifacts:
        reports:
            junit:
                - junit-report.xml
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
        paths:
            - junit-report.xml
            - coverage.xml
        expire_in: 1 hour
    needs: [ ]

sonarqube:
    stage: quality assurance
    variables:
        SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
        GIT_STRATEGY: fetch
        GIT_DEPTH: 0
    script:
        - /hri/sit/latest/External/SonarScanner/4.6/bin/sonar-scanner
    cache:
        key: "${CI_JOB_NAME}"
        paths:
            - .sonar/cache
    needs:
        - lint
        - unit tests
